/**
 * Universal Certification, Academy & Organization Logo Dataset
 * Curated registry of 60+ top academies, learning platforms, universities, and enterprise ecosystems.
 */

export interface OrganizationLogoEntry {
  id: string;
  name: string;
  category: 'cloud' | 'mooc' | 'ai' | 'university' | 'ecosystem';
  iconKey: string;
  brandColor: string;
  aliases: string[];
  domains: string[];
  websiteUrl: string;
}

export const CERTIFICATION_CATEGORIES = [
  { id: 'all', label: 'All Organizations' },
  { id: 'cloud', label: 'Cloud & Enterprise' },
  { id: 'mooc', label: 'Online MOOCs & Bootcamps' },
  { id: 'ai', label: 'AI & Data Institutes' },
  { id: 'university', label: 'Universities & Academies' },
  { id: 'ecosystem', label: 'Developer Ecosystems' },
] as const;

export const CERTIFICATION_LOGOS: OrganizationLogoEntry[] = [
  // ── 1. Cloud & Enterprise ─────────────────────────────────────
  {
    id: 'aws',
    name: 'Amazon Web Services',
    category: 'cloud',
    iconKey: 'aws',
    brandColor: '#FF9900',
    aliases: ['aws', 'amazon web services', 'amazon aws', 'aws training'],
    domains: ['aws.amazon.com', 'aws.training', 'amazon.com'],
    websiteUrl: 'https://aws.amazon.com',
  },
  {
    id: 'gcp',
    name: 'Google Cloud',
    category: 'cloud',
    iconKey: 'gcp',
    brandColor: '#4285F4',
    aliases: ['google cloud', 'gcp', 'google cloud platform', 'google cloud skills boost'],
    domains: ['cloud.google.com', 'cloudskillsboost.google'],
    websiteUrl: 'https://cloud.google.com',
  },
  {
    id: 'azure',
    name: 'Microsoft Azure',
    category: 'cloud',
    iconKey: 'azure',
    brandColor: '#0078D4',
    aliases: ['microsoft azure', 'azure', 'microsoft learn', 'microsoft certified'],
    domains: ['azure.microsoft.com', 'learn.microsoft.com'],
    websiteUrl: 'https://azure.microsoft.com',
  },
  {
    id: 'ibm',
    name: 'IBM',
    category: 'cloud',
    iconKey: 'ibm',
    brandColor: '#052FAD',
    aliases: ['ibm', 'ibm cloud', 'ibm skillsbuild', 'ibm training'],
    domains: ['ibm.com', 'skillsbuild.org'],
    websiteUrl: 'https://www.ibm.com',
  },
  {
    id: 'oracle',
    name: 'Oracle',
    category: 'cloud',
    iconKey: 'oracle',
    brandColor: '#F80000',
    aliases: ['oracle', 'oracle cloud', 'oracle university'],
    domains: ['oracle.com', 'mylearn.oracle.com'],
    websiteUrl: 'https://www.oracle.com',
  },
  {
    id: 'hashicorp',
    name: 'HashiCorp',
    category: 'cloud',
    iconKey: 'hashicorp',
    brandColor: '#000000',
    aliases: ['hashicorp', 'terraform', 'vault', 'consul'],
    domains: ['hashicorp.com', 'developer.hashicorp.com'],
    websiteUrl: 'https://www.hashicorp.com',
  },
  {
    id: 'redhat',
    name: 'Red Hat',
    category: 'cloud',
    iconKey: 'redhat',
    brandColor: '#EE0000',
    aliases: ['red hat', 'redhat', 'rhce', 'rhcsa', 'openshift'],
    domains: ['redhat.com'],
    websiteUrl: 'https://www.redhat.com',
  },
  {
    id: 'cisco',
    name: 'Cisco',
    category: 'cloud',
    iconKey: 'cisco',
    brandColor: '#1BA0D7',
    aliases: ['cisco', 'cisco networking academy', 'ccna', 'ccnp', 'netacad'],
    domains: ['cisco.com', 'netacad.com'],
    websiteUrl: 'https://www.cisco.com',
  },
  {
    id: 'vmware',
    name: 'VMware',
    category: 'cloud',
    iconKey: 'vmware',
    brandColor: '#607078',
    aliases: ['vmware', 'vmware certified', 'broadcom vmware'],
    domains: ['vmware.com', 'broadcom.com'],
    websiteUrl: 'https://www.vmware.com',
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    category: 'cloud',
    iconKey: 'snowflake',
    brandColor: '#29B5E8',
    aliases: ['snowflake', 'snowpro', 'snowflake data cloud'],
    domains: ['snowflake.com', 'learn.snowflake.com'],
    websiteUrl: 'https://www.snowflake.com',
  },
  {
    id: 'databricks',
    name: 'Databricks',
    category: 'cloud',
    iconKey: 'databricks',
    brandColor: '#FF3621',
    aliases: ['databricks', 'databricks academy', 'apache spark'],
    domains: ['databricks.com', 'academy.databricks.com'],
    websiteUrl: 'https://www.databricks.com',
  },
  {
    id: 'salesforce',
    name: 'Salesforce (Trailhead)',
    category: 'cloud',
    iconKey: 'salesforce',
    brandColor: '#00A1E0',
    aliases: ['salesforce', 'trailhead', 'trailblazer', 'salesforce certified'],
    domains: ['salesforce.com', 'trailhead.salesforce.com'],
    websiteUrl: 'https://trailhead.salesforce.com',
  },
  {
    id: 'linux',
    name: 'Linux Foundation',
    category: 'cloud',
    iconKey: 'linux',
    brandColor: '#FCC624',
    aliases: ['linux foundation', 'linux', 'lfc', 'lfcs', 'lfce'],
    domains: ['linuxfoundation.org', 'training.linuxfoundation.org'],
    websiteUrl: 'https://www.linuxfoundation.org',
  },
  {
    id: 'kubernetes',
    name: 'CNCF / Kubernetes',
    category: 'cloud',
    iconKey: 'kubernetes',
    brandColor: '#326CE5',
    aliases: ['kubernetes', 'cncf', 'cka', 'ckad', 'cks', 'cloud native computing foundation'],
    domains: ['kubernetes.io', 'cncf.io'],
    websiteUrl: 'https://kubernetes.io',
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'cloud',
    iconKey: 'docker',
    brandColor: '#2496ED',
    aliases: ['docker', 'docker certified associate', 'dca'],
    domains: ['docker.com'],
    websiteUrl: 'https://www.docker.com',
  },

  // ── 2. Online MOOCs & Coding Bootcamps ────────────────────────
  {
    id: 'coursera',
    name: 'Coursera',
    category: 'mooc',
    iconKey: 'coursera',
    brandColor: '#0056D2',
    aliases: ['coursera', 'coursera verified', 'coursera certificate'],
    domains: ['coursera.org'],
    websiteUrl: 'https://www.coursera.org',
  },
  {
    id: 'udemy',
    name: 'Udemy',
    category: 'mooc',
    iconKey: 'udemy',
    brandColor: '#A435F0',
    aliases: ['udemy', 'udemy certificate', 'udemy business'],
    domains: ['udemy.com'],
    websiteUrl: 'https://www.udemy.com',
  },
  {
    id: 'edx',
    name: 'edX',
    category: 'mooc',
    iconKey: 'edx',
    brandColor: '#02262B',
    aliases: ['edx', 'edx verified', 'edx microbootcamp'],
    domains: ['edx.org'],
    websiteUrl: 'https://www.edx.org',
  },
  {
    id: 'udacity',
    name: 'Udacity',
    category: 'mooc',
    iconKey: 'udacity',
    brandColor: '#01B3E3',
    aliases: ['udacity', 'udacity nanodegree', 'nanodegree'],
    domains: ['udacity.com'],
    websiteUrl: 'https://www.udacity.com',
  },
  {
    id: 'pluralsight',
    name: 'Pluralsight',
    category: 'mooc',
    iconKey: 'pluralsight',
    brandColor: '#F15B2A',
    aliases: ['pluralsight', 'pluralsight skills'],
    domains: ['pluralsight.com'],
    websiteUrl: 'https://www.pluralsight.com',
  },
  {
    id: 'datacamp',
    name: 'DataCamp',
    category: 'mooc',
    iconKey: 'datacamp',
    brandColor: '#03EF62',
    aliases: ['datacamp', 'datacamp statement of accomplishment'],
    domains: ['datacamp.com'],
    websiteUrl: 'https://www.datacamp.com',
  },
  {
    id: 'codecademy',
    name: 'Codecademy',
    category: 'mooc',
    iconKey: 'codecademy',
    brandColor: '#1F4056',
    aliases: ['codecademy', 'codecademy career path'],
    domains: ['codecademy.com'],
    websiteUrl: 'https://www.codecademy.com',
  },
  {
    id: 'freecodecamp',
    name: 'freeCodeCamp',
    category: 'mooc',
    iconKey: 'freecodecamp',
    brandColor: '#0A0A23',
    aliases: ['freecodecamp', 'free code camp', 'fcc'],
    domains: ['freecodecamp.org'],
    websiteUrl: 'https://www.freecodecamp.org',
  },
  {
    id: 'scrimba',
    name: 'Scrimba',
    category: 'mooc',
    iconKey: 'scrimba',
    brandColor: '#2B283A',
    aliases: ['scrimba', 'the frontend career path'],
    domains: ['scrimba.com'],
    websiteUrl: 'https://scrimba.com',
  },
  {
    id: 'kaggle',
    name: 'Kaggle',
    category: 'mooc',
    iconKey: 'kaggle',
    brandColor: '#20BEFF',
    aliases: ['kaggle', 'kaggle microcourses', 'kaggle learn'],
    domains: ['kaggle.com'],
    websiteUrl: 'https://www.kaggle.com',
  },
  {
    id: 'leetcode',
    name: 'LeetCode',
    category: 'mooc',
    iconKey: 'leetcode',
    brandColor: '#FFA116',
    aliases: ['leetcode', 'leetcode study plan', 'leetcode contest badge'],
    domains: ['leetcode.com'],
    websiteUrl: 'https://leetcode.com',
  },
  {
    id: 'hackerrank',
    name: 'HackerRank',
    category: 'mooc',
    iconKey: 'hackerrank',
    brandColor: '#2EC866',
    aliases: ['hackerrank', 'hackerrank certified', 'hackerrank skill certificate'],
    domains: ['hackerrank.com'],
    websiteUrl: 'https://www.hackerrank.com',
  },
  {
    id: 'khanacademy',
    name: 'Khan Academy',
    category: 'mooc',
    iconKey: 'khanacademy',
    brandColor: '#14BF96',
    aliases: ['khan academy', 'khanacademy'],
    domains: ['khanacademy.org'],
    websiteUrl: 'https://www.khanacademy.org',
  },
  {
    id: 'linkedinlearning',
    name: 'LinkedIn Learning',
    category: 'mooc',
    iconKey: 'linkedin',
    brandColor: '#0A66C2',
    aliases: ['linkedin learning', 'lynda.com', 'linkedin certificate of completion'],
    domains: ['linkedin.com/learning'],
    websiteUrl: 'https://www.linkedin.com/learning',
  },
  {
    id: 'brilliant',
    name: 'Brilliant',
    category: 'mooc',
    iconKey: 'brilliant',
    brandColor: '#000000',
    aliases: ['brilliant', 'brilliant.org'],
    domains: ['brilliant.org'],
    websiteUrl: 'https://brilliant.org',
  },

  // ── 3. AI & Data Institutes ───────────────────────────────────
  {
    id: 'anthropic',
    name: 'Anthropic / Claude Academy',
    category: 'ai',
    iconKey: 'anthropic',
    brandColor: '#D97757',
    aliases: ['anthropic', 'claude', 'claude developer academy', 'constitutional ai', 'claude 3'],
    domains: ['anthropic.com', 'claude.ai'],
    websiteUrl: 'https://www.anthropic.com',
  },
  {
    id: 'openai',
    name: 'OpenAI Academy',
    category: 'ai',
    iconKey: 'openai',
    brandColor: '#10A37F',
    aliases: ['openai', 'openai developers', 'chatgpt', 'openai academy', 'gpt-4'],
    domains: ['openai.com', 'chatgpt.com'],
    websiteUrl: 'https://openai.com',
  },
  {
    id: 'googleai',
    name: 'Google DeepMind & AI Studio',
    category: 'ai',
    iconKey: 'googleai',
    brandColor: '#4285F4',
    aliases: ['deepmind', 'google deepmind', 'google-ai', 'gemini', 'google ai studio', 'vertex ai'],
    domains: ['deepmind.google', 'ai.google.dev'],
    websiteUrl: 'https://deepmind.google',
  },
  {
    id: 'metaai',
    name: 'Meta AI / PyTorch Foundation',
    category: 'ai',
    iconKey: 'pytorch',
    brandColor: '#EE4C2C',
    aliases: ['meta ai', 'pytorch', 'pytorch foundation', 'llama', 'meta ai research'],
    domains: ['ai.meta.com', 'pytorch.org'],
    websiteUrl: 'https://pytorch.org',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'ai',
    iconKey: 'mistral',
    brandColor: '#FA520F',
    aliases: ['mistral', 'mistral ai', 'mistral academy', 'la plateforme', 'codestral'],
    domains: ['mistral.ai'],
    websiteUrl: 'https://mistral.ai',
  },
  {
    id: 'cohere',
    name: 'Cohere LLM University',
    category: 'ai',
    iconKey: 'cohere',
    brandColor: '#39594C',
    aliases: ['cohere', 'cohere llm university', 'cohere ai', 'command r'],
    domains: ['cohere.com', 'docs.cohere.com'],
    websiteUrl: 'https://cohere.com',
  },
  {
    id: 'langchain',
    name: 'LangChain Academy',
    category: 'ai',
    iconKey: 'langchain',
    brandColor: '#1C3C3C',
    aliases: ['langchain', 'langsmith', 'langgraph', 'langchain academy', 'langchain certified'],
    domains: ['langchain.com', 'academy.langchain.com'],
    websiteUrl: 'https://academy.langchain.com',
  },
  {
    id: 'llamaindex',
    name: 'LlamaIndex',
    category: 'ai',
    iconKey: 'llamaindex',
    brandColor: '#7B2CBF',
    aliases: ['llamaindex', 'llama-index', 'llama-parse', 'llamacloud'],
    domains: ['llamaindex.ai', 'docs.llamaindex.ai'],
    websiteUrl: 'https://www.llamaindex.ai',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Academy',
    category: 'ai',
    iconKey: 'huggingface',
    brandColor: '#FFD21E',
    aliases: ['hugging face', 'huggingface', 'hf audio/nlp course', 'hugging face certified'],
    domains: ['huggingface.co'],
    websiteUrl: 'https://huggingface.co',
  },
  {
    id: 'deeplearning',
    name: 'DeepLearning.AI',
    category: 'ai',
    iconKey: 'deeplearning',
    brandColor: '#FF6F00',
    aliases: ['deeplearning.ai', 'deeplearning', 'andrew ng', 'deep learning specialization', 'short courses'],
    domains: ['deeplearning.ai'],
    websiteUrl: 'https://www.deeplearning.ai',
  },
  {
    id: 'wandb',
    name: 'Weights & Biases Academy',
    category: 'ai',
    iconKey: 'wandb',
    brandColor: '#FFBE00',
    aliases: ['weights & biases', 'wandb', 'w&b', 'weights & biases academy'],
    domains: ['wandb.ai'],
    websiteUrl: 'https://wandb.ai',
  },
  {
    id: 'fastai',
    name: 'fast.ai',
    category: 'ai',
    iconKey: 'fastai',
    brandColor: '#000000',
    aliases: ['fast.ai', 'practical deep learning for coders', 'jeremy howard'],
    domains: ['fast.ai'],
    websiteUrl: 'https://www.fast.ai',
  },
  {
    id: 'nvidia',
    name: 'NVIDIA Deep Learning Institute (DLI)',
    category: 'ai',
    iconKey: 'nvidia',
    brandColor: '#76B900',
    aliases: ['nvidia', 'nvidia dli', 'deep learning institute', 'nvidia certified'],
    domains: ['nvidia.com', 'courses.nvidia.com'],
    websiteUrl: 'https://www.nvidia.com/en-us/training/',
  },
  {
    id: 'pinecone',
    name: 'Pinecone Academy',
    category: 'ai',
    iconKey: 'pinecone',
    brandColor: '#000000',
    aliases: ['pinecone', 'pinecone academy', 'vector database certified'],
    domains: ['pinecone.io'],
    websiteUrl: 'https://www.pinecone.io',
  },
  {
    id: 'qdrant',
    name: 'Qdrant Vector Search',
    category: 'ai',
    iconKey: 'qdrant',
    brandColor: '#DC2626',
    aliases: ['qdrant', 'qdrant vector database', 'qdrant certified'],
    domains: ['qdrant.tech'],
    websiteUrl: 'https://qdrant.tech',
  },
  {
    id: 'weaviate',
    name: 'Weaviate Academy',
    category: 'ai',
    iconKey: 'weaviate',
    brandColor: '#00D2B4',
    aliases: ['weaviate', 'weaviate academy', 'weaviate vector search'],
    domains: ['weaviate.io'],
    websiteUrl: 'https://weaviate.io',
  },
  {
    id: 'databricksai',
    name: 'Databricks Generative AI Academy',
    category: 'ai',
    iconKey: 'databricks',
    brandColor: '#FF3621',
    aliases: ['databricks-ai', 'databricks generative ai engineer', 'databricks certified genai', 'databricks'],
    domains: ['databricks.com', 'academy.databricks.com'],
    websiteUrl: 'https://www.databricks.com',
  },

  // ── 4. Global & Regional Universities ─────────────────────────
  {
    id: 'stanford',
    name: 'Stanford University (Stanford Online)',
    category: 'university',
    iconKey: 'stanford',
    brandColor: '#8C1515',
    aliases: ['stanford', 'stanford university', 'stanford online', 'stanford engineering'],
    domains: ['stanford.edu', 'online.stanford.edu'],
    websiteUrl: 'https://online.stanford.edu',
  },
  {
    id: 'mit',
    name: 'MIT (MITx / OpenCourseWare)',
    category: 'university',
    iconKey: 'mit',
    brandColor: '#A31F34',
    aliases: ['mit', 'massachusetts institute of technology', 'mitx', 'mit opencourseware'],
    domains: ['mit.edu', 'mitxonline.mit.edu', 'ocw.mit.edu'],
    websiteUrl: 'https://www.mit.edu',
  },
  {
    id: 'harvard',
    name: 'Harvard University (HarvardX / CS50)',
    category: 'university',
    iconKey: 'harvard',
    brandColor: '#A51C30',
    aliases: ['harvard', 'harvard university', 'harvardx', 'cs50'],
    domains: ['harvard.edu', 'harvardx.harvard.edu'],
    websiteUrl: 'https://www.harvard.edu',
  },
  {
    id: 'oxford',
    name: 'University of Oxford',
    category: 'university',
    iconKey: 'oxford',
    brandColor: '#002147',
    aliases: ['oxford', 'university of oxford', 'oxford online'],
    domains: ['ox.ac.uk'],
    websiteUrl: 'https://www.ox.ac.uk',
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    category: 'university',
    iconKey: 'cambridge',
    brandColor: '#A3C1AD',
    aliases: ['cambridge', 'university of cambridge'],
    domains: ['cam.ac.uk'],
    websiteUrl: 'https://www.cam.ac.uk',
  },
  {
    id: 'berkeley',
    name: 'UC Berkeley (BerkeleyX)',
    category: 'university',
    iconKey: 'berkeley',
    brandColor: '#003262',
    aliases: ['uc berkeley', 'berkeley', 'berkeleyx', 'university of california berkeley'],
    domains: ['berkeley.edu'],
    websiteUrl: 'https://www.berkeley.edu',
  },
  {
    id: 'cmu',
    name: 'Carnegie Mellon University',
    category: 'university',
    iconKey: 'cmu',
    brandColor: '#C41230',
    aliases: ['cmu', 'carnegie mellon', 'carnegie mellon university'],
    domains: ['cmu.edu'],
    websiteUrl: 'https://www.cmu.edu',
  },
  {
    id: 'chula',
    name: 'Chulalongkorn University (CU MOOC)',
    category: 'university',
    iconKey: 'chula',
    brandColor: '#DE4B86',
    aliases: ['chulalongkorn university', 'chulalongkorn', 'chula', 'cu mooc', 'cu'],
    domains: ['chula.ac.th', 'mooc.chula.ac.th'],
    websiteUrl: 'https://www.chula.ac.th',
  },
  {
    id: 'mahidol',
    name: 'Mahidol University (MUx)',
    category: 'university',
    iconKey: 'mahidol',
    brandColor: '#0047BA',
    aliases: ['mahidol university', 'mahidol', 'mux'],
    domains: ['mahidol.ac.th', 'mux.mahidol.ac.th'],
    websiteUrl: 'https://mahidol.ac.th',
  },
  {
    id: 'ku',
    name: 'Kasetsart University',
    category: 'university',
    iconKey: 'ku',
    brandColor: '#006A4E',
    aliases: ['kasetsart university', 'kasetsart', 'ku'],
    domains: ['ku.ac.th'],
    websiteUrl: 'https://www.ku.ac.th',
  },
  {
    id: 'kmutt',
    name: 'KMUTT (King Mongkut University of Technology Thonburi)',
    category: 'university',
    iconKey: 'kmutt',
    brandColor: '#FA4616',
    aliases: ['kmutt', 'king mongkut university of technology thonburi', 'bangmod'],
    domains: ['kmutt.ac.th'],
    websiteUrl: 'https://www.kmutt.ac.th',
  },

  // ── 5. Developer Ecosystems & Databases ────────────────────────
  {
    id: 'meta',
    name: 'Meta (Meta Professional Certificates)',
    category: 'ecosystem',
    iconKey: 'meta',
    brandColor: '#0668E1',
    aliases: ['meta', 'facebook', 'meta front-end developer', 'meta back-end developer'],
    domains: ['meta.com', 'about.meta.com'],
    websiteUrl: 'https://about.meta.com',
  },
  {
    id: 'apple',
    name: 'Apple Developer Academy',
    category: 'ecosystem',
    iconKey: 'apple',
    brandColor: '#000000',
    aliases: ['apple', 'apple developer', 'swift', 'apple developer academy'],
    domains: ['apple.com', 'developer.apple.com'],
    websiteUrl: 'https://developer.apple.com',
  },
  {
    id: 'stripe',
    name: 'Stripe Certified',
    category: 'ecosystem',
    iconKey: 'stripe',
    brandColor: '#635BFF',
    aliases: ['stripe', 'stripe certified professional', 'stripe payments'],
    domains: ['stripe.com'],
    websiteUrl: 'https://stripe.com',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'ecosystem',
    iconKey: 'supabase',
    brandColor: '#3ECF8E',
    aliases: ['supabase', 'supabase developer'],
    domains: ['supabase.com'],
    websiteUrl: 'https://supabase.com',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'ecosystem',
    iconKey: 'vercel',
    brandColor: '#000000',
    aliases: ['vercel', 'next.js certified'],
    domains: ['vercel.com', 'nextjs.org'],
    websiteUrl: 'https://vercel.com',
  },
  {
    id: 'prisma',
    name: 'Prisma ORM',
    category: 'ecosystem',
    iconKey: 'prisma',
    brandColor: '#2D3748',
    aliases: ['prisma', 'prisma orm', 'prisma data guide'],
    domains: ['prisma.io'],
    websiteUrl: 'https://www.prisma.io',
  },
  {
    id: 'mongodb',
    name: 'MongoDB University',
    category: 'ecosystem',
    iconKey: 'mongodb',
    brandColor: '#47A248',
    aliases: ['mongodb', 'mongodb university', 'mongodb certified developer', 'mongodb certified dba'],
    domains: ['mongodb.com', 'learn.mongodb.com'],
    websiteUrl: 'https://learn.mongodb.com',
  },
  {
    id: 'redis',
    name: 'Redis University',
    category: 'ecosystem',
    iconKey: 'redis',
    brandColor: '#DC382D',
    aliases: ['redis', 'redis university', 'redis certified developer'],
    domains: ['redis.io', 'university.redis.com'],
    websiteUrl: 'https://university.redis.com',
  },
];

export function getAllCertificationLogos(): OrganizationLogoEntry[] {
  return CERTIFICATION_LOGOS;
}

export function getLogosByCategory(category: string): OrganizationLogoEntry[] {
  if (!category || category === 'all') return CERTIFICATION_LOGOS;
  return CERTIFICATION_LOGOS.filter((item) => item.category === category);
}

export function findLogoById(id: string): OrganizationLogoEntry | undefined {
  return CERTIFICATION_LOGOS.find(
    (item) => item.id.toLowerCase() === id.toLowerCase() || item.iconKey.toLowerCase() === id.toLowerCase()
  );
}
