// ── Recommendation presets shown as clickable chips on admin pages ──
// Covers the full spectrum of what modern CVs & resumes list.

export const SKILL_SUGGESTIONS = [
  // ── Frontend ──────────────────────────────────────────────
  { name: 'React',               proficiency: 85, category: 'Frontend' },
  { name: 'Next.js',             proficiency: 80, category: 'Frontend' },
  { name: 'TypeScript',          proficiency: 80, category: 'Frontend' },
  { name: 'JavaScript',          proficiency: 90, category: 'Frontend' },
  { name: 'HTML / CSS',          proficiency: 95, category: 'Frontend' },
  { name: 'Tailwind CSS',        proficiency: 85, category: 'Frontend' },
  { name: 'Vue.js',              proficiency: 75, category: 'Frontend' },
  { name: 'Angular',             proficiency: 65, category: 'Frontend' },
  { name: 'Svelte',              proficiency: 60, category: 'Frontend' },
  { name: 'Redux',               proficiency: 75, category: 'Frontend' },
  { name: 'React Query',         proficiency: 70, category: 'Frontend' },
  { name: 'Framer Motion',       proficiency: 70, category: 'Frontend' },
  { name: 'Responsive Design',   proficiency: 90, category: 'Frontend' },
  { name: 'Accessibility (a11y)',proficiency: 70, category: 'Frontend' },
  { name: 'SASS / SCSS',         proficiency: 80, category: 'Frontend' },
  // ── Backend ───────────────────────────────────────────────
  { name: 'Node.js',             proficiency: 75, category: 'Backend' },
  { name: 'Express.js',          proficiency: 75, category: 'Backend' },
  { name: 'Python',              proficiency: 70, category: 'Backend' },
  { name: 'FastAPI',             proficiency: 65, category: 'Backend' },
  { name: 'Django',              proficiency: 60, category: 'Backend' },
  { name: 'REST API Design',     proficiency: 80, category: 'Backend' },
  { name: 'GraphQL',             proficiency: 65, category: 'Backend' },
  { name: 'Java',                proficiency: 60, category: 'Backend' },
  { name: 'Spring Boot',         proficiency: 55, category: 'Backend' },
  { name: 'Go (Golang)',         proficiency: 55, category: 'Backend' },
  { name: 'PHP / Laravel',       proficiency: 60, category: 'Backend' },
  { name: 'WebSockets',          proficiency: 65, category: 'Backend' },
  { name: 'Authentication / JWT',proficiency: 75, category: 'Backend' },
  { name: 'Microservices',       proficiency: 65, category: 'Backend' },
  // ── Database ──────────────────────────────────────────────
  { name: 'PostgreSQL',          proficiency: 75, category: 'Database' },
  { name: 'MySQL',               proficiency: 70, category: 'Database' },
  { name: 'MongoDB',             proficiency: 65, category: 'Database' },
  { name: 'Prisma ORM',          proficiency: 75, category: 'Database' },
  { name: 'Redis',               proficiency: 60, category: 'Database' },
  { name: 'SQLite',              proficiency: 70, category: 'Database' },
  { name: 'Supabase',            proficiency: 70, category: 'Database' },
  { name: 'Firebase',            proficiency: 70, category: 'Database' },
  { name: 'ElasticSearch',       proficiency: 55, category: 'Database' },
  { name: 'Database Design',     proficiency: 75, category: 'Database' },
  // ── DevOps / Cloud ────────────────────────────────────────
  { name: 'Docker',              proficiency: 70, category: 'DevOps' },
  { name: 'Kubernetes',          proficiency: 55, category: 'DevOps' },
  { name: 'Git & GitHub',        proficiency: 90, category: 'DevOps' },
  { name: 'CI/CD Pipelines',     proficiency: 65, category: 'DevOps' },
  { name: 'AWS',                 proficiency: 60, category: 'DevOps' },
  { name: 'Google Cloud (GCP)',  proficiency: 60, category: 'DevOps' },
  { name: 'Azure',               proficiency: 55, category: 'DevOps' },
  { name: 'Vercel',              proficiency: 85, category: 'DevOps' },
  { name: 'Linux / Bash',        proficiency: 70, category: 'DevOps' },
  { name: 'Nginx',               proficiency: 65, category: 'DevOps' },
  { name: 'Terraform',           proficiency: 55, category: 'DevOps' },
  // ── Design ────────────────────────────────────────────────
  { name: 'Figma',               proficiency: 75, category: 'Design' },
  { name: 'UI/UX Design',        proficiency: 70, category: 'Design' },
  { name: 'Adobe XD',            proficiency: 60, category: 'Design' },
  { name: 'Adobe Photoshop',     proficiency: 65, category: 'Design' },
  { name: 'Wireframing',         proficiency: 75, category: 'Design' },
  { name: 'Prototyping',         proficiency: 70, category: 'Design' },
  { name: 'Design Systems',      proficiency: 70, category: 'Design' },
  // ── AI / ML ───────────────────────────────────────────────
  { name: 'Machine Learning',    proficiency: 60, category: 'AI/ML' },
  { name: 'LLM Integration',     proficiency: 65, category: 'AI/ML' },
  { name: 'Prompt Engineering',  proficiency: 70, category: 'AI/ML' },
  { name: 'TensorFlow',          proficiency: 55, category: 'AI/ML' },
  { name: 'PyTorch',             proficiency: 55, category: 'AI/ML' },
  { name: 'Data Analysis',       proficiency: 65, category: 'AI/ML' },
  { name: 'Computer Vision',     proficiency: 55, category: 'AI/ML' },
  { name: 'NLP',                 proficiency: 55, category: 'AI/ML' },
  // ── Soft Skills ───────────────────────────────────────────
  { name: 'Agile / Scrum',       proficiency: 80, category: 'Soft Skills' },
  { name: 'Problem Solving',     proficiency: 90, category: 'Soft Skills' },
  { name: 'Communication',       proficiency: 85, category: 'Soft Skills' },
  { name: 'Leadership',          proficiency: 75, category: 'Soft Skills' },
  { name: 'Team Collaboration',  proficiency: 85, category: 'Soft Skills' },
  { name: 'Time Management',     proficiency: 80, category: 'Soft Skills' },
  { name: 'Critical Thinking',   proficiency: 85, category: 'Soft Skills' },
  { name: 'Project Management',  proficiency: 75, category: 'Soft Skills' },
  { name: 'Mentoring',           proficiency: 70, category: 'Soft Skills' },
  { name: 'Public Speaking',     proficiency: 65, category: 'Soft Skills' },
  // ── Testing ───────────────────────────────────────────────
  { name: 'Jest',                proficiency: 70, category: 'Testing' },
  { name: 'React Testing Library',proficiency: 70, category: 'Testing' },
  { name: 'Cypress',             proficiency: 65, category: 'Testing' },
  { name: 'Unit Testing',        proficiency: 75, category: 'Testing' },
  { name: 'E2E Testing',         proficiency: 65, category: 'Testing' },
];

export const HOBBY_SUGGESTIONS = [
  { name: 'Photography',     emoji: '📸' },
  { name: 'Gaming',          emoji: '🎮' },
  { name: 'Reading',         emoji: '📚' },
  { name: 'Hiking',          emoji: '🥾' },
  { name: 'Cooking',         emoji: '🍳' },
  { name: 'Music',           emoji: '🎵' },
  { name: 'Drawing',         emoji: '✏️' },
  { name: 'Traveling',       emoji: '✈️' },
  { name: 'Gym / Fitness',   emoji: '💪' },
  { name: 'Cycling',         emoji: '🚴' },
  { name: 'Chess',           emoji: '♟️' },
  { name: 'Writing',         emoji: '✍️' },
  { name: 'Swimming',        emoji: '🏊' },
  { name: 'Baking',          emoji: '🧁' },
  { name: 'Yoga',            emoji: '🧘' },
  { name: 'Surfing',         emoji: '🏄' },
  { name: 'Football',        emoji: '⚽' },
  { name: 'Basketball',      emoji: '🏀' },
  { name: 'Rock Climbing',   emoji: '🧗' },
  { name: 'Gardening',       emoji: '🌱' },
  { name: 'Podcasting',      emoji: '🎙️' },
  { name: 'Film Making',     emoji: '🎬' },
  { name: 'Origami',         emoji: '🦢' },
  { name: 'Dancing',         emoji: '💃' },
  { name: 'Badminton',       emoji: '🏸' },
  { name: 'Table Tennis',    emoji: '🏓' },
  { name: 'Running',         emoji: '🏃' },
  { name: 'Volunteering',    emoji: '🤝' },
  { name: 'Blogging',        emoji: '📝' },
  { name: 'Painting',        emoji: '🎨' },
  { name: 'Guitar',          emoji: '🎸' },
  { name: 'Piano',           emoji: '🎹' },
];

export const INTEREST_CATEGORIES = [
  'Engineering & Core Tech',
  'Domain & Industry',
  'Personal & Disciplines',
] as const;

export const INTEREST_SUGGESTIONS = [
  // ── Engineering & Core Tech ─────────────────────────────────
  { name: 'AI Agents & LLMs',        emoji: '🤖', category: 'Engineering & Core Tech' },
  { name: 'System Architecture',     emoji: '🏗️', category: 'Engineering & Core Tech' },
  { name: 'Distributed Computing',   emoji: '⚡', category: 'Engineering & Core Tech' },
  { name: 'Database Systems',        emoji: '🗄️', category: 'Engineering & Core Tech' },
  { name: 'Cloud & Kubernetes',      emoji: '☁️', category: 'Engineering & Core Tech' },
  { name: 'Web Performance',         emoji: '🚀', category: 'Engineering & Core Tech' },
  { name: 'Cybersecurity',           emoji: '🔐', category: 'Engineering & Core Tech' },
  { name: 'Quantum Computing',       emoji: '⚛️', category: 'Engineering & Core Tech' },
  { name: 'Open Source Development', emoji: '🌐', category: 'Engineering & Core Tech' },

  // ── Domain & Industry ───────────────────────────────────────
  { name: 'FinTech & DeFi',          emoji: '💰', category: 'Domain & Industry' },
  { name: 'HealthTech & BioTech',    emoji: '🏥', category: 'Domain & Industry' },
  { name: 'Developer Tooling & DX',  emoji: '🛠️', category: 'Domain & Industry' },
  { name: 'Enterprise SaaS',         emoji: '🏢', category: 'Domain & Industry' },
  { name: 'EdTech & Learning',       emoji: '🎓', category: 'Domain & Industry' },
  { name: 'GreenTech & Energy',      emoji: '🌱', category: 'Domain & Industry' },
  { name: 'Space Technology',        emoji: '🌌', category: 'Domain & Industry' },

  // ── Personal & Disciplines ──────────────────────────────────
  { name: 'Weightlifting & Fitness', emoji: '🏋️', category: 'Personal & Disciplines' },
  { name: 'Chess Strategy',          emoji: '♟️', category: 'Personal & Disciplines' },
  { name: 'Astronomy & Astrophysics',emoji: '🔭', category: 'Personal & Disciplines' },
  { name: 'Language Acquisition',    emoji: '🗣️', category: 'Personal & Disciplines' },
  { name: 'Philosophy of Mind',      emoji: '🧠', category: 'Personal & Disciplines' },
  { name: 'Product Design & UI/UX',  emoji: '🎨', category: 'Personal & Disciplines' },
];

// defaultProficiency is used to pre-select the dropdown when the chip is clicked
export const LANGUAGE_SUGGESTIONS = [
  { name: 'English',          flag: '🇬🇧', defaultProficiency: 'Fluent' },
  { name: 'Thai',             flag: '🇹🇭', defaultProficiency: 'Native' },
  { name: 'Mandarin Chinese', flag: '🇨🇳', defaultProficiency: 'Intermediate' },
  { name: 'Japanese',         flag: '🇯🇵', defaultProficiency: 'Basic' },
  { name: 'Korean',           flag: '🇰🇷', defaultProficiency: 'Basic' },
  { name: 'French',           flag: '🇫🇷', defaultProficiency: 'Intermediate' },
  { name: 'German',           flag: '🇩🇪', defaultProficiency: 'Intermediate' },
  { name: 'Spanish',          flag: '🇪🇸', defaultProficiency: 'Intermediate' },
  { name: 'Portuguese',       flag: '🇵🇹', defaultProficiency: 'Basic' },
  { name: 'Hindi',            flag: '🇮🇳', defaultProficiency: 'Basic' },
  { name: 'Arabic',           flag: '🇸🇦', defaultProficiency: 'Basic' },
  { name: 'Russian',          flag: '🇷🇺', defaultProficiency: 'Basic' },
  { name: 'Indonesian',       flag: '🇮🇩', defaultProficiency: 'Intermediate' },
  { name: 'Vietnamese',       flag: '🇻🇳', defaultProficiency: 'Basic' },
  { name: 'Malay',            flag: '🇲🇾', defaultProficiency: 'Basic' },
  { name: 'Italian',          flag: '🇮🇹', defaultProficiency: 'Basic' },
  { name: 'Dutch',            flag: '🇳🇱', defaultProficiency: 'Basic' },
  { name: 'Burmese',          flag: '🇲🇲', defaultProficiency: 'Basic' },
  { name: 'Khmer',            flag: '🇰🇭', defaultProficiency: 'Basic' },
];

export const SOCIAL_SUGGESTIONS = [
  { platform: 'GitHub',        placeholderUrl: 'https://github.com/username', icon: '🐙' },
  { platform: 'LinkedIn',      placeholderUrl: 'https://linkedin.com/in/username', icon: '💼' },
  { platform: 'Instagram',     placeholderUrl: 'https://instagram.com/username', icon: '📸' },
  { platform: 'X / Twitter',   placeholderUrl: 'https://x.com/username', icon: '🐦' },
  { platform: 'Discord',       placeholderUrl: 'https://discord.gg/yourserver', icon: '💬' },
  { platform: 'Email',         placeholderUrl: 'mailto:your.email@example.com', icon: '✉️' },
  { platform: 'YouTube',       placeholderUrl: 'https://youtube.com/@channel', icon: '🎥' },
  { platform: 'Telegram',      placeholderUrl: 'https://t.me/username', icon: '✈️' },
  { platform: 'Medium / Blog', placeholderUrl: 'https://medium.com/@username', icon: '✍️' },
  { platform: 'Spotify',       placeholderUrl: 'https://open.spotify.com/user/...', icon: '🎧' },
  { platform: 'Portfolio / Web', placeholderUrl: 'https://yourwebsite.com', icon: '🌐' },
];
